### ISSUE TITLE
Precio de las habitaciones

### ISSUE THREAD

**Issue by yoinergomez** [yoinergomez/dae_hotelz_ionic#13]
La moneda es de tipo COP, no debería aparecer los centavos.

![captura](https://user-images.githubusercontent.com/14276026/32643293-6b135cc8-c5a8-11e7-9ce7-caa113a1d857.PNG)

**Comment by camigomez35** [comment]
<img width="281" alt="captura de pantalla 2017-11-10 a la s 3 21 18 p m" src="https://user-images.githubusercontent.com/16061815/32677125-3ec5527e-c62b-11e7-9d23-9ea41a5b8645.png">
